apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: hello-react
  name: hello-react
spec:
  source:
    git:
      ref: master
      uri: https://github.com/sjp147/hello-react.git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  triggers:
    - github:
        secret: secret
      type: GitHub
    - generic:
        secret: secret
      type: Generic
    - bitbucket:
        secret: secret
      type: Bitbucket
