pipeline {

    agent {
        kubernetes {
        label 'jenkins-slave'
        defaultContainer 'jnlp'
        yaml """
apiVersion: v1
kind: Pod
spec:
    containers:
    - name: jnlp
      image: openshift/jenkins-agent-nodejs-8-centos7:v3.11
      tty: true
    - name: tools
      image: argoproj/argo-cd-ci-builder:latest
      command:
      - cat
      tty: true
        """
        }
    }

    environment {
        APPLICATION_NAME = 'hello-react'
        GIT_REPO="https://github.com/sjp147/hello-react.git"
        GIT_BRANCH="master"
        STAGE_TAG = "promoteToQA"
        CICD_PROJECT="cicd"
        DEV_PROJECT = "dev"
        STAGE_PROJECT = "stage"
        TEMPLATE_NAME = "hello-react"
        ARTIFACT_FOLDER = "target"
        PORT = 8081;
        GIT_COMMITTER_NAME = "Jenkins"
        GIT_COMMITTER_EMAIL = "Jenkins@openshift"
        //GIT_SSH="ssh -i /ssh/ssh-privatekey"
    }
    stages {
        stage('Get Latest Code') {
            steps {
                git branch: "${GIT_BRANCH}", url: "${GIT_REPO}"
            }
        }

        stage('git test') {

            steps {
               
                    container('tools') {



                        withCredentials([sshUserPrivateKey(credentialsId: "cicd-bitbucket", keyFileVariable: 'KEYFILE')]) {


                            sh '''

                            echo "#!/bin/bash

                            ID_RSA=\"$KEYFILE\"

                            ssh -o UserKnownHostsFile=/dev/null -i $ID_RSA $1 $2" > ssh-wrapper.sh

                            chmod 777 ssh-wrapper.sh

                            ./sshwrapper.sh -T git@hithub.com



                            '''
                                }
                            

            
                
                        

                    
                    
                    
                    
            }
            }
        }

        stage('Create web app'){
            steps{
                    dir("app") {

                            sh "npm ci"
                            sh "npm run build"

                    }
            }
        }

         stage('Store web app'){
            steps{
                script{
                    def safeBuildName  = "${APPLICATION_NAME}_${BUILD_NUMBER}",
                        artifactFolder = "${ARTIFACT_FOLDER}",
                        fullFileName   = "${safeBuildName}.tar.gz",
                        applicationZip = "${artifactFolder}/${fullFileName}"
                        applicationDir = ["app/build",
                                            "container/nginx.conf",
                                            "Dockerfile",
                                            ].join(" ");
                    def needTargetPath = !fileExists("${artifactFolder}")
                    if (needTargetPath) {
                        sh "mkdir ${artifactFolder}"
                    }
                    sh "tar -czvf ${applicationZip} ${applicationDir}"
                    archiveArtifacts artifacts: "${applicationZip}", excludes: null, onlyIfSuccessful: true
                }
            }
        }


        stage('Create Image Builder') {
            when {
                expression {
                    openshift.withCluster() {
                        openshift.withProject(DEV_PROJECT) {
                            return !openshift.selector("bc", "${TEMPLATE_NAME}").exists();
                        }
                }
            }
        }
        steps {
            script {
                openshift.withCluster() {
                    openshift.withProject(DEV_PROJECT) {
                        openshift.newBuild("--name=${TEMPLATE_NAME}", "--docker-image=docker.io/nginx:mainline-alpine", "--binary=true")
                        }
                    }
                }
            }
        }

        stage('Build Image') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(env.DEV_PROJECT) {
                            openshift.selector("bc", "$TEMPLATE_NAME").startBuild("--from-archive=${ARTIFACT_FOLDER}/${APPLICATION_NAME}_${BUILD_NUMBER}.tar.gz", "--wait=true")
                        }
                    }
                }
            }
        }

        stage('Deploy to dev') {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject(env.DEV_PROJECT) {

                        openshift.tag("${APPLICATION_NAME}:latest", "${APPLICATION_NAME}:${env.GIT_COMMIT}") 
                        }
                    }
                }
                    container('tools') {
                          sh "env"
                      
                    //sh 'git clone https://$GIT_CREDS_USR:$GIT_CREDS_PSW@github.com/sjp147/hello-config.git'
                    
                    
                        withCredentials([sshUserPrivateKey(credentialsId: "cicd-bitbucket", keyFileVariable: 'KEYFILE')]) {

                    sh "GIT_SSH_COMMAND='ssh -i $KEYFILE' git clone ssh://git@github.com/sjp147/hello-config.git"
                    dir("hello-config") {
 
                       sh "git config user.email 'you@example.com'"
                                              sh "git config user.name 'Jenkins'"


                        sh "cd ./dev && kustomize edit set image 172.30.1.1:5000/dev/hello-react:${env.GIT_COMMIT}"
                        sh "git diff"
                        sh "GIT_SSH='ssh -i $KEYFILE' git commit -am 'Publish new version' && GIT_SSH='ssh -i $KEYFILE' git push || echo 'no changes'"
                    }
                        

                    }

                        withCredentials([string(credentialsId: "argocd-deploy", variable: 'ARGOCD_AUTH_TOKEN')]) {

                        sh "ARGOCD_SERVER=argocd-server-argocd.192.168.64.7.nip.io argocd --grpc-web app sync hello-react --force --insecure"
                        sh "ARGOCD_SERVER=argocd-server-argocd.192.168.64.7.nip.io argocd --grpc-web app wait hello-react --timeout 60 --insecure"
                                        }
                    
                    
            }

        }

    }
}
}
