apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: hello-react-pipeline
  name: hello-react-pipeline
spec:
  source:
    git:
      ref: master
      uri: 'ssh://git@github.com/sjp147/hello-react.git'
    sourceSecret:
      name: bitbucket
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipeline/Jenkinsfile
    type: JenkinsPipeline
